apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.yml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**
            - id: reg-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/v1/register/**
            - id: user-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/v1/user/**
              #filters:
              #  - RewritePath=(/?.*)/api/user, /api/v1/user
