apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.yml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**
            - id: reg-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/v1/register/**
            - id: user-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/v1/user/**
            - id: menu-service
              uri: http://menu-service:8080
              predicates:
                - Path=/api/v1/menu/**
            - id: order-service
              uri: http://order-service:8080
              predicates:
                - Path=/api/v1/order/**
            - id: payment-service
              uri: http://payment-service:8080
              predicates:
                - Path=/api/v1/account/**
