apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.auth_gateway.image }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth_gateway.config.jwt.secretName }}
                  key: secret

            - name: JWT_EXPIRATIONINMS
              value: {{ .Values.auth_gateway.config.jwt.expirationInMs | quote }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 6
          args:
            - "--spring.config.additional-location=/config/config.yml"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
