apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      {{- if eq .Values.postgresql.service.type "NodePort" }}
      nodePort: {{ .Values.postgresql.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-postgres