service:
  port: 8080

replicaCount: 1

notification_service:
  image: podomnina/notification-service:9
  config:
    kafka:
      bootstrapServers: my-kafka.otus.svc.cluster.local:9092
    mail:
      host: smtp.rambler.ru
      port: 465
      protocol: smtp
      secretName: notification-service-email-secret
      username: podomninatest@rambler.ru
      password: Bakamitai17
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"