apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pg-secret
type: Opaque
data:
  username: {{ .Values.menu_service.config.db.username | b64enc | quote }}
  password: {{ .Values.menu_service.config.db.password | b64enc | quote }}