apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}