server:
  port: 8083

spring:
  application:
    name: notification-service
  mail:
    host: smtp.yandex.ru
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    protocol: smtp
    properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
    default-encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    enable:
      timed: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
