service:
  port: 8080

replicaCount: 1

inventory_service:
  image: podomnina/inventory-service:8
  config:
    db:
      url: jdbc:postgresql://otus-postgres-postgres:5432/inventory
      secretName: inventory-service-pg-secret
      username: otus_user
      password: NVB1c6hB6vF7
    redis:
      host: redis.redis.svc.cluster.local
      port: 6379
      password: password #todo
    kafka:
      bootstrapServers: otus-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"