apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: {{ .Release.Name }}-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http