apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-email-secret
type: Opaque
data:
  username: {{ .Values.notification_service.config.mail.username | b64enc | quote }}
  password: {{ .Values.notification_service.config.mail.password | b64enc | quote }}