server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${db.url}
    user: ${db.username}
    password: ${db.password}
    locations:
      - classpath:db
    schemas:
      - auth

db:
  url:
  username:
  password: