service:
  port: 8080

replicaCount: 1

order_service:
  image: podomnina/order-service:12
  config:
    db:
      url: jdbc:postgresql://otus-postgres-postgres:5432/otus
      secretName: order-service-pg-secret
      username: otus_user
      password: NVB1c6hB6vF7
    cart:
      ttl: 60 # todo
    redis:
      host: redis
      port: 6379
      password: password #todo
    kafka:
      bootstrapServers: my-kafka.otus.svc.cluster.local:9092

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"